name = "LiquidsStructure"
uuid = "3b2fbd69-638f-58f2-a86a-379d5727c4f6"
authors = ["Pablo Zubieta, Jesús Zepeda"]
version = "0.1.0"

[compat]
julia = "≥ 1.0.0"

[deps]
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
